/**
 * AngularCourse
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserReadSmallSchema } from './userReadSmallSchema';
import { CommentReadSchema } from './commentReadSchema';


export interface CommentReadWithChildSchema { 
    id: number;
    text: string;
    author: UserReadSmallSchema;
    postId: number;
    commentId?: number | null;
    createdAt: string;
    updatedAt?: string | null;
    comments: Array<CommentReadSchema>;
}

