/**
 * AngularCourse
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserReadSchemaShort } from './userReadSchemaShort';


export interface PageUserReadSchemaShort { 
    items: Array<UserReadSchemaShort>;
    total: number | null;
    page: number | null;
    size: number | null;
    pages?: number | null;
}

