/**
 * AngularCourse
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MessageReadSchema } from './messageReadSchema';
import { UserReadSchemaShort } from './userReadSchemaShort';


export interface PersonalChatReadSchema { 
    id: number;
    userFirst: UserReadSchemaShort;
    userSecond: UserReadSchemaShort;
    messages?: Array<MessageReadSchema> | null;
}

